version: "3.8"
services:
  postgres:
    image: postgres
    container_name: JumpMapEloPostgres
    # Secrets can be hard coded since the DB is not internet facing
    environment:
      - POSTGRES_USER=imdb
      - POSTGRES_PASSWORD=imdb123
      - POSTGRES_DB=imdb_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  imdb-import:
    build:
      dockerfile: src/JumpMapElo.Blazor
      context: .
    image: jump-map-elo
    container_name: JumpMapEloBlazor
    restart: unless-stopped
    environment:
      - ASPNETCORE_ConnectionStrings__Marten=User ID = imdb;Password=imdb123;Server=postgres;Port=5432;Database=imdb_db;Integrated Security=true;Pooling=true